import { test,expect } from '@playwright/test';
import { credentials,eventName } from '../scripts/e2e-fixtures.mjs';
import { createCanvas,loadImage } from '@napi-rs/canvas';
import jsQR from 'jsqr';
test.beforeEach(async({page})=>{
  await page.goto('/login');
  await page.getByLabel('Correo electrónico').fill(credentials.correo);
  await page.getByLabel('Contraseña',{exact:true}).fill(credentials.password);
  await page.getByRole('button',{name:'Iniciar sesión'}).click();
  await expect(page.getByRole('heading',{name:'El pulso de tu evento.'})).toBeVisible();
  await page.getByRole('navigation',{name:'Navegación principal',exact:true}).getByText('Ventas y asistentes').click();
  await expect(page.getByRole('heading',{name:'Cada entrada cuenta.'})).toBeVisible();
});
test('venta, pago, boleto QR, exportaciones filtradas y anulación',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.getByRole('button',{name:'Registrar Venta',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('Nombre completo').fill('Valeria Prueba Ventas');
  await dialog.getByLabel('Teléfono').fill('7777-0101');
  await dialog.getByLabel('Colegio / Senior').fill('Colegio Integración');
  await dialog.getByLabel('Cantidad',{exact:true}).fill('2');
  await dialog.getByLabel('Transferencia',{exact:true}).check();
  await dialog.getByRole('combobox',{name:'Estado de pago',exact:true}).selectOption('PENDIENTE');
  await expect(dialog.locator('.sale-total')).toContainText('$30.00');
  await page.screenshot({path:'test-results/sale-form-desktop.png',fullPage:true});
  await dialog.getByRole('button',{name:'Registrar venta',exact:true}).click();
  await expect(dialog).toHaveCount(0);
  await page.getByLabel('Buscar ventas').fill('Valeria Prueba Ventas');
  await expect(page.locator('.sales-table tbody tr')).toHaveCount(1);
  await expect(page.locator('.sales-table tbody tr')).toContainText('Pendiente');
  await page.getByRole('button',{name:'Editar venta de Valeria Prueba Ventas'}).click();
  await page.getByRole('dialog').getByRole('combobox',{name:'Estado de pago',exact:true}).selectOption('CANCELADO');
  await page.getByRole('dialog').getByLabel('Referencia de comprobante').fill('TRANSFER-TEST-001');
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.sales-table tbody tr')).toContainText('Pagado');
  await page.screenshot({path:'test-results/sales-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Ver boleto de Valeria Prueba Ventas'}).click();
  const qr=page.locator('.ticket-readable-qr');
  await expect(qr).toBeVisible();
  const url=await qr.getAttribute('src');const image=await loadImage(Buffer.from(url.split(',')[1],'base64'));
  const canvas=createCanvas(image.width,image.height);const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);
  const pixels=ctx.getImageData(0,0,image.width,image.height);const decoded=jsQR(pixels.data,image.width,image.height);
  expect(decoded.data).toMatch(/^NEXO:NX[A-F0-9]{24}$/);
  await expect(page.getByRole('dialog')).toContainText(eventName);
  await page.screenshot({path:'test-results/ticket-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Cerrar ventana'}).click();
  const pdfPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar PDF'}).click();const pdf=await pdfPromise;await pdf.saveAs('test-results/ventas-filtradas.pdf');
  const csvPromise=page.waitForEvent('download');await page.getByRole('button',{name:'CSV',exact:true}).click();const csv=await csvPromise;await csv.saveAs('test-results/ventas-filtradas.csv');
  await page.getByRole('button',{name:'Anular venta de Valeria Prueba Ventas'}).click();
  await page.getByLabel('Motivo de anulación').fill('Solicitud del asistente de prueba');
  await page.getByRole('button',{name:'Confirmar anulación'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('group',{name:'Filtrar por estado'}).getByRole('button',{name:'Anuladas',exact:true}).click();
  await expect(page.locator('.sales-table tbody tr')).toContainText('Anulada');
  await expect(page.getByRole('button',{name:'Editar venta de Valeria Prueba Ventas'})).toBeDisabled();
  expect(errors).toEqual([]);
});
test('filtros y modal funcionan en móvil con la paleta azul acero',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('.sales-table tbody tr').first()).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/sales-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Registrar Venta',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/sale-form-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Cerrar ventana'}).click();
  await page.getByRole('group',{name:'Filtrar por categoría'}).getByRole('button',{name:'Promo',exact:true}).click();
  await expect(page.locator('.sales-table tbody tr')).toHaveCount(1);
  await expect(page.locator('.sales-table tbody tr')).toContainText('Transferencia de prueba');
});
